// Generated by gencpp from file test/detector.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_DETECTOR_H
#define TEST_MESSAGE_DETECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct detector_
{
  typedef detector_<ContainerAllocator> Type;

  detector_()
    : x(0)
    , y(0)
    , height(0)
    , width(0)
    , arrow(0)  {
    }
  detector_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , height(0)
    , width(0)
    , arrow(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _arrow_type;
  _arrow_type arrow;





  typedef boost::shared_ptr< ::test::detector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::detector_<ContainerAllocator> const> ConstPtr;

}; // struct detector_

typedef ::test::detector_<std::allocator<void> > detector;

typedef boost::shared_ptr< ::test::detector > detectorPtr;
typedef boost::shared_ptr< ::test::detector const> detectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::detector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::detector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::detector_<ContainerAllocator1> & lhs, const ::test::detector_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.arrow == rhs.arrow;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::detector_<ContainerAllocator1> & lhs, const ::test::detector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::detector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::detector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee01ea2a195a728d9a98b72b946d52d6";
  }

  static const char* value(const ::test::detector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee01ea2a195a728dULL;
  static const uint64_t static_value2 = 0x9a98b72b946d52d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/detector";
  }

  static const char* value(const ::test::detector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 height\n"
"int32 width\n"
"int32 arrow\n"
;
  }

  static const char* value(const ::test::detector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::detector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.arrow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::detector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::detector_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "arrow: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arrow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_DETECTOR_H
